# Generated by Django 4.2.21 on 2025-05-14 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje_usuario', models.TextField()),
                ('respuesta_ia', models.TextField()),
                ('emocion_detectada', models.CharField(blank=True, max_length=50, null=True)),
                ('tema', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
