# Generated by Django 4.2.21 on 2025-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaccion',
            name='respuesta_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
